Vagrant.configure("2") do |config|
  
  # Servidor HAProxy + Consul Server
  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "ubuntu/focal64"
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "192.168.56.10"
    haproxy.vm.provision "shell", path: "scripts/provision-haproxy-consul.sh"
  end

  # Web1 con Consul Client y App Node.js
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/focal64"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.56.11"
    web1.vm.provision "shell", path: "scripts/provision-consul-client.sh"
  end

  # Web2 con Consul Client y App Node.js
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/focal64"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.56.12"
    web2.vm.provision "shell", path: "scripts/provision-consul-client.sh"
  end
end